name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"   # runs once a day
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Generate snake animation
        uses: Platane/snk@v3
        with:
          github_user_name: Manjan855
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Copy output to a clean writable folder
        run: |
          mkdir -p ${{ runner.temp }}/snake-output
          sudo cp -r dist/. ${{ runner.temp }}/snake-output/
          sudo chown -R $(whoami) ${{ runner.temp }}/snake-output

      - name: Push snake svg to output branch
        run: |
          cd ${{ runner.temp }}/snake-output
          git init
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git checkout -b output
          git add -A
          git commit -m "Update snake animation" --allow-empty
          git push -f https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git output
